import { useMemo, useState } from "react";
import "./FreshAIHome.css";
import { createFreshAIWorkspaceContext } from "../../../core/fresh-ai/FreshAIWorkspaceContext";
import "../../../core/ara6/bootstrap";

type Mode = "chat" | "research" | "create" | "build" | "learn" | "act";
const modes: Array<[Mode,string,string]> = [["chat","Chat","Ask anything"],["research","Research","Search and verify"],["create","Create","Write and generate"],["build","Build","Code and ship"],["learn","Learn","Learn with context"],["act","Act","Use approved tools"]];
const powers = [["Understand","Goal, context and intent"],["Memory","Conversation and durable memory"],["Research","Web, sources and evidence"],["Reason","Analysis, planning and trade-offs"],["Create","Text, image, video and audio"],["Communicate","Chat, translate and connect"],["Automate","Multi-step workflows"],["Verify","Truth, provenance and confidence"],["Act","Governed tool execution"]];
const surfaces = [["Chat & Connect","Conversations, people, translation and continuity"],["Workspace","Projects, files, tasks and decisions"],["Design & Creator","Visual, audio and video creation"],["Code & Software","Build, debug, test and deploy"],["Research","Investigate, compare and verify"],["Academy","Teach, practice and remember"],["Wallet & Trust","Risk, security and verification"],["Automation","Goals into governed workflows"]];
function openFresh(prompt?: string){window.dispatchEvent(new CustomEvent("fresh-ai-open",{detail:{prompt}}));}
export default function FreshAIHome(){
 const [mode,setMode]=useState<Mode>("chat"); const [prompt,setPrompt]=useState(""); const [voice,setVoice]=useState(false); const context=useMemo(()=>createFreshAIWorkspaceContext(window.location.pathname),[]);
 const submit=()=>{const p=prompt.trim();openFresh(p||undefined);if(p)setPrompt("");};
 return <main className="fresh-ai-home-v3">
  <header className="fai-header"><div className="fai-mark">F</div><div className="fai-heading"><span>FRESH AI</span><h1>One intelligence. Everywhere.</h1><p>Ask anything. Fresh can then research, create, build, learn, coordinate or act with the context of what you are doing.</p></div><div className="fai-header-actions"><button className={voice?"on":""} onClick={()=>setVoice(v=>!v)}>◉ {voice?"Voice on":"Voice"}</button><button onClick={()=>openFresh()}>Open ↗</button></div></header>
  <section className="fai-composer"><div className="fai-status"><b>● Fresh AI ready</b><span>{context.featureName} · {context.surface}</span><span>{context.capabilities.length} capabilities</span><span>{context.toolNamespaces.length} tool spaces</span></div><div className="fai-input"><button onClick={()=>openFresh("Use the current context and available tools to help me.")} aria-label="Add context">＋</button><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit();}}} placeholder={`${modes.find(m=>m[0]===mode)?.[2]} with Fresh AI…`}/><button onClick={()=>setVoice(v=>!v)} aria-label="Voice">{voice?"●":"◉"}</button><button className="send" onClick={submit} aria-label="Send">↑</button></div><div className="fai-modes">{modes.map(([id,label])=><button key={id} className={mode===id?"active":""} onClick={()=>{setMode(id);if(id!=="chat")setPrompt(`${label}: `)}}>{label}</button>)}<span>Fresh Auto · context aware</span></div></section>
  <section className="fai-layout"><div>
   <div className="fai-section-title"><span>CAPABILITY FABRIC</span><h2>Everything Fresh AI can bring to the conversation</h2></div>
   <div className="fai-power-grid">{powers.map(([name,desc])=><button key={name} onClick={()=>openFresh(`Use your ${name.toLowerCase()} capability to help me. ${desc}.`)}><strong>{name}</strong><small>{desc}</small><i>›</i></button>)}</div>
   <div className="fai-section-title surfaces"><span>AI EVERYWHERE</span><h2>Open Fresh in any part of Fresh</h2></div>
   <div className="fai-surface-grid">{surfaces.map(([name,desc])=><button key={name} onClick={()=>openFresh(`I am working in ${name}. ${desc}. Help me here.`)}><strong>{name}</strong><small>{desc}</small><b>Use Fresh here →</b></button>)}</div>
  </div><aside>
   <section className="fai-panel"><div className="fai-panel-head"><span>ACTIVE CONTEXT</span><b>LIVE</b></div><h3>{context.featureName}</h3><p>Fresh carries this context into the same intelligence gateway used everywhere else.</p><dl><div><dt>Surface</dt><dd>{context.surface}</dd></div><div><dt>Feature</dt><dd>{context.featureId}</dd></div><div><dt>Model</dt><dd>{context.activeModelId}</dd></div><div><dt>Voice</dt><dd>{context.activeVoiceModelId}</dd></div></dl><button onClick={()=>openFresh("What can you do for me in this exact space?")}>Ask about this space →</button></section>
   <section className="fai-panel"><div className="fai-panel-head"><span>MODELS & VOICE</span><b>{context.models.filter(m=>m.available).length} READY</b></div>{context.models.map(m=><div className="fai-model" key={m.id}><span>{m.family==="voice"?"◉":"✦"}</span><div><strong>{m.name}</strong><small>{m.family} · {m.capabilities.slice(0,4).join(" · ")}</small></div><i>{m.available?"Ready":"Off"}</i></div>)}<button onClick={()=>openFresh("Choose the best available model for what I want to do.")}>Choose model →</button></section>
   <section className="fai-panel"><div className="fai-panel-head"><span>GOVERNED INTELLIGENCE</span><b>ACTIVE</b></div><div className="fai-path">{["Understand","Memory","Research","Reason","Tools","Verify"].map(x=><span key={x}>{x}</span>)}</div><p>Truth, safety, approval boundaries and verification remain behind every surface.</p></section>
  </aside></section>
  <footer><b>Fresh AI · one identity</b><span>Memory · Knowledge · Research · Truth · Skills · Models · Voice · Tools · ARA6 · Verification</span></footer>
 </main>;
}
