import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { useLayout } from "../contexts/useLayout";
import { useTheme } from "../providers/ThemeProvider";
import { supabase } from "../../lib/supabase";
import { createFreshAIWorkspaceContext } from "../../core/fresh-ai/FreshAIWorkspaceContext";
import "./FreshAIUnified.css";

type Turn={role:"user"|"assistant";content:string;createdAt:string};
type Evidence={title:string;snippet?:string};
type AskPayload={requestId?:string;answer?:string;error?:string;source?:string;evidence?:Evidence[];intent?:string;image?:{dataUrl:string;model:string;size:string};persistence?:{configured?:boolean;inserted?:number;error?:string}};
const modes=["Chat","Research","Create","Build","Learn","Act"] as const;

export default function FreshAIUnified(){
  const {activeRoute}=useLayout(); const {theme,toggle}=useTheme();
  const context=useMemo(()=>createFreshAIWorkspaceContext(activeRoute??"/"),[activeRoute]);
  const isAI=(activeRoute??"").replace(/\/$/,"").toLowerCase()==="/ai";
  const [open,setOpen]=useState(isAI),[draft,setDraft]=useState(""),[turns,setTurns]=useState<Turn[]>([]),[mode,setMode]=useState<(typeof modes)[number]>("Chat"),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[image,setImage]=useState<AskPayload["image"]>(),[requestId,setRequestId]=useState<string|null>(null),[source,setSource]=useState<string|null>(null);
  const endRef=useRef<HTMLDivElement|null>(null); const inputRef=useRef<HTMLTextAreaElement|null>(null);
  useEffect(()=>{if(isAI)setOpen(true)},[isAI]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[turns,loading]);
  useEffect(()=>{const handler=(e:Event)=>{const p=(e as CustomEvent<{prompt?:string}>).detail?.prompt;if(p){setDraft(p);setOpen(true);requestAnimationFrame(()=>inputRef.current?.focus())}};window.addEventListener("fresh-ai-open",handler);return()=>window.removeEventListener("fresh-ai-open",handler)},[]);
  async function ask(e?:FormEvent){e?.preventDefault();const goal=draft.trim();if(!goal||loading)return;const now=new Date().toISOString();const previous=turns.slice(-8);setTurns(v=>[...v,{role:"user",content:goal,createdAt:now},{role:"assistant",content:"",createdAt:new Date().toISOString()}]);setDraft("");setLoading(true);setError(null);setEvidence([]);setImage(undefined);setSource(null);
    try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const r=await fetch("/api/ai/ask",{method:"POST",headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({goal,route:activeRoute??"/",mode:mode.toLowerCase(),conversation:previous,workspaceContext:context,image:mode==="Create"?{size:"1024x1024",quality:"auto"}:undefined})});const payload=await r.json() as AskPayload;if(!r.ok)throw new Error(payload.error||`Fresh AI request failed (${r.status})`);const answer=payload.answer||"Fresh AI completed the request.";setTurns(v=>{const copy=[...v],last=copy[copy.length-1];if(last?.role==="assistant")copy[copy.length-1]={...last,content:answer};return copy});setRequestId(payload.requestId??null);setSource(payload.source??"Fresh AI");setEvidence(Array.isArray(payload.evidence)?payload.evidence:[]);setImage(payload.image)}catch(reason){const message=reason instanceof Error?reason.message:"Fresh AI could not complete that request.";setError(message);setTurns(v=>v[v.length-1]?.role==="assistant"&&!v[v.length-1].content?v.slice(0,-1):v)}finally{setLoading(false)}}
  function suggestion(text:string){setDraft(text);setOpen(true);requestAnimationFrame(()=>inputRef.current?.focus())}
  const body=<div className="fresh-ai-unified-shell"><header><div className="fresh-ai-unified-brand"><span className="fresh-ai-unified-orb">F</span><div><strong>Fresh AI</strong><small>One intelligence. Everywhere.</small></div></div><div className="fresh-ai-unified-actions"><span>{context.featureName}</span><button type="button" onClick={toggle}>{theme==="dark"?"☀":"☾"}</button>{!isAI&&<button type="button" onClick={()=>setOpen(false)}>×</button>}</div></header><div className="fresh-ai-unified-context">{context.surface} · {context.route} · Context-aware Fresh AI</div><section className="fresh-ai-unified-messages">{turns.length===0?<div className="fresh-ai-unified-welcome"><span>F</span><h2>What can Fresh help you do?</h2><p>Chat, research, create, build, learn or act through the same Fresh AI intelligence.</p><div>{["Understand something","Research this","Create an image","Help me build this"].map(x=><button key={x} type="button" onClick={()=>suggestion(x)}>{x}</button>)}</div></div>:turns.map((t,i)=><article key={`${t.createdAt}-${i}`} className={`fresh-ai-unified-message ${t.role}`}><div className="fresh-ai-unified-avatar">{t.role==="assistant"?"F":"You"}</div><div><small>{t.role==="assistant"?"Fresh AI":"You"}</small><p>{t.content||"Thinking…"}</p>{t.role==="assistant"&&i===turns.length-1&&t.content&&<nav><button type="button" onClick={()=>navigator.clipboard?.writeText(t.content)}>Copy</button><button type="button" onClick={()=>suggestion(turns.filter(x=>x.role==="user").at(-1)?.content||"")}>Regenerate</button></nav>}</div></article>)}{evidence.length>0&&<aside className="fresh-ai-unified-evidence"><strong>Evidence</strong>{evidence.map((item,i)=><div key={`${item.title}-${i}`}><span>{item.title}</span>{item.snippet&&<small>{item.snippet}</small>}</div>)}</aside>}{image&&<div className="fresh-ai-unified-image"><img src={image.dataUrl} alt="Generated by Fresh AI"/><small>{image.model} · {image.size}</small></div>}{error&&<div className="fresh-ai-unified-error">{error}</div>}<div ref={endRef}/></section><div className="fresh-ai-unified-composer"><div className="fresh-ai-unified-modes">{modes.map(x=><button key={x} className={mode===x?"active":""} type="button" onClick={()=>setMode(x)}>{x}</button>)}</div><form onSubmit={ask}><textarea ref={inputRef} rows={1} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Message Fresh AI…"/><div><span>{loading?"Fresh is working…":"Enter to send · Shift+Enter for a new line"}</span>{loading?<button type="button" onClick={()=>setLoading(false)}>Stop</button>:<button type="submit" disabled={!draft.trim()}>↑</button>}</div></form><small className="fresh-ai-unified-status">{source||"Fresh AI"}{requestId?` · ${requestId.slice(0,8)}`:""} · Memory · Knowledge · Tools · Verification</small></div></div>;
  if(isAI)return <main className="fresh-ai-unified-page">{body}</main>;
  return <>{!open&&<button className="fresh-ai-unified-trigger" type="button" onClick={()=>setOpen(true)}><span>F</span>Fresh AI</button>}{open&&<div className="fresh-ai-unified-overlay" role="dialog" aria-label="Fresh AI">{body}</div>}</>;
}
