import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from "react";
import { useLayout } from "../contexts/useLayout";
import { useTheme } from "../providers/ThemeProvider";
import { supabase } from "../../lib/supabase";
import { createFreshAIWorkspaceContext } from "../../core/fresh-ai/FreshAIWorkspaceContext";
import "./FreshAIMain.css";

type Turn = { role: "user" | "assistant"; content: string; createdAt: string };
type Evidence = { title: string; snippet?: string };
type StreamEvent = { type?: string; text?: string; error?: string; evidence?: Evidence[]; model?: string };
const modes = ["Chat", "Research", "Create", "Build", "Learn", "Act"] as const;
function cleanError(text: string, status: number) { try { const value = JSON.parse(text) as { error?: unknown }; if (typeof value.error === "string") return value.error; } catch { /* plain text */ } return text.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim().slice(0, 500) || `Fresh AI request failed (${status}).`; }
export default function FreshAIMain() {
  const { activeRoute } = useLayout(); const { theme, toggle } = useTheme(); const context = useMemo(() => createFreshAIWorkspaceContext(activeRoute ?? "/ai"), [activeRoute]);
  const [turns, setTurns] = useState<Turn[]>([]), [draft, setDraft] = useState(""), [mode, setMode] = useState<(typeof modes)[number]>("Chat"), [loading, setLoading] = useState(false), [error, setError] = useState<string | null>(null), [source, setSource] = useState<string | null>(null), [evidence, setEvidence] = useState<Evidence[]>([]), [files, setFiles] = useState<File[]>([]), [model, setModel] = useState("fresh-auto"), [voice, setVoice] = useState(false);
  const abortRef = useRef<AbortController | null>(null), endRef = useRef<HTMLDivElement | null>(null), composerRef = useRef<HTMLTextAreaElement | null>(null), messagesRef = useRef<HTMLDivElement | null>(null), stickRef = useRef(true);
  useEffect(() => { if (stickRef.current) endRef.current?.scrollIntoView({ behavior: loading ? "auto" : "smooth", block: "end" }); }, [turns, loading]);
  useEffect(() => { const open = (e: Event) => { const p = (e as CustomEvent<{ prompt?: string }>).detail?.prompt; if (p) { setDraft(p); requestAnimationFrame(() => composerRef.current?.focus()); } }; window.addEventListener("fresh-ai-open", open); return () => window.removeEventListener("fresh-ai-open", open); }, []);
  function onScroll() { const el = messagesRef.current; if (!el) return; stickRef.current = el.scrollHeight - el.scrollTop - el.clientHeight < 100; }
  function resize() { const el = composerRef.current; if (!el) return; el.style.height = "auto"; el.style.height = `${Math.min(el.scrollHeight, 180)}px`; }
  async function ask(e?: FormEvent) {
    e?.preventDefault(); const goal = draft.trim(); if (!goal || loading) return; const userTurn = { role: "user" as const, content: goal, createdAt: new Date().toISOString() }; setTurns(v => [...v, userTurn, { role: "assistant", content: "", createdAt: new Date().toISOString() }]); setDraft(""); requestAnimationFrame(resize); setLoading(true); setError(null); setSource(null); setEvidence([]); stickRef.current = true; const controller = new AbortController(); abortRef.current = controller;
    try { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; const response = await fetch("/api/ai/live-stream", { method: "POST", signal: controller.signal, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ goal, route: activeRoute ?? "/ai", mode: mode.toLowerCase(), model, voiceModel: context.activeVoiceModelId, workspaceContext: context, conversation: turns.slice(-8), attachments: files.map(f => ({ name: f.name, type: f.type, size: f.size })) }) }); if (!response.ok || !response.body) throw new Error(cleanError(await response.text(), response.status)); const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = ""; while (true) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const lines = buffer.split(/\r?\n/); buffer = lines.pop() || ""; for (const line of lines) { if (!line.startsWith("data:")) continue; const raw = line.slice(5).trim(); if (!raw) continue; let item: StreamEvent; try { item = JSON.parse(raw) as StreamEvent; } catch { continue; } if (item.type === "token" && item.text) setTurns(v => { const copy = [...v], last = copy[copy.length - 1]; if (last?.role === "assistant") copy[copy.length - 1] = { ...last, content: last.content + item.text }; return copy; }); if (item.type === "start") setSource(item.model ? `Model: ${item.model}` : "Fresh AI"); if (item.type === "done") setEvidence(Array.isArray(item.evidence) ? item.evidence : []); if (item.type === "error") throw new Error(item.error || "Fresh AI streaming failed."); } } }
    catch (r) { if (r instanceof DOMException && r.name === "AbortError") return; setError(r instanceof Error ? r.message : "Fresh AI could not complete that request."); setTurns(v => { const last = v[v.length - 1]; return last?.role === "assistant" && !last.content ? v.slice(0, -1) : v; }); }
    finally { abortRef.current = null; setLoading(false); }
  }
  function stop() { abortRef.current?.abort(); setLoading(false); }
  function keyDown(e: KeyboardEvent<HTMLTextAreaElement>) { if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); void ask(); } }
  async function copy(text: string) { try { await navigator.clipboard.writeText(text); } catch { /* unavailable */ } }
  function regenerate() { const u = [...turns].reverse().find(t => t.role === "user"); if (u && !loading) { setDraft(u.content); requestAnimationFrame(() => composerRef.current?.focus()); } }
  function speak(text: string) { if (typeof window !== "undefined" && "speechSynthesis" in window) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(text)); } }
  return <main className="fresh-ai-main"><header className="fresh-ai-main-header"><div className="fresh-ai-main-brand"><span>F</span><div><h1>Fresh AI</h1><p>One intelligence. Everywhere.</p></div></div><div className="fresh-ai-main-actions"><span>{context.featureName}</span><select aria-label="AI model" value={model} onChange={e => setModel(e.target.value)}><option value="fresh-auto">Fresh Auto</option><option value="gemini-2.5-flash">Gemini 2.5 Flash</option></select><button type="button" onClick={toggle}>{theme === "dark" ? "☀" : "☾"}</button></div></header>
    <section className="fresh-ai-conversation"><div className="fresh-ai-messages" ref={messagesRef} onScroll={onScroll}>{turns.length === 0 ? <div className="fresh-ai-welcome"><span>F</span><h2>What can Fresh help you do?</h2><p>Ask anything. Fresh chooses context, capabilities, models, knowledge and tools for the job.</p><div>{["Understand something", "Research this", "Create with me", "Help me build this"].map(x => <button key={x} type="button" onClick={() => { setDraft(x); requestAnimationFrame(() => composerRef.current?.focus()); }}>{x}</button>)}</div></div> : turns.map((t, i) => <article className={`fresh-ai-message ${t.role}`} key={`${t.createdAt}-${i}`}><div className="fresh-ai-avatar">{t.role === "assistant" ? "F" : "You"}</div><div><small>{t.role === "assistant" ? "Fresh AI" : "You"}</small><div className="fresh-ai-text">{t.content || (loading ? "" : "No response")}</div>{t.role === "assistant" && t.content && <nav><button type="button" onClick={() => void copy(t.content)}>Copy</button><button type="button" onClick={regenerate}>Regenerate</button><button type="button" onClick={() => speak(t.content)}>Read aloud</button></nav>}{t.role === "assistant" && loading && i === turns.length - 1 && !t.content && <div className="fresh-ai-thinking"><i/><i/><i/> Thinking…</div>}</div></article>)}{error && <div className="fresh-ai-error"><strong>Fresh AI couldn't complete that request.</strong><span>{error}</span><button type="button" onClick={() => { const u = [...turns].reverse().find(t => t.role === "user"); setError(null); if (u) { setDraft(u.content); requestAnimationFrame(() => composerRef.current?.focus()); } }}>Retry</button></div>}{source && <div className="fresh-ai-meta">{source} · {context.surface}</div>}{evidence.length > 0 && <details><summary>{evidence.length} evidence items used</summary>{evidence.map((x, i) => <div key={`${x.title}-${i}`}><b>{x.title}</b>{x.snippet && <span>{x.snippet}</span>}</div>)}</details>}<div ref={endRef}/></div>
      <div className="fresh-ai-composer-area"><div className="fresh-ai-modes">{modes.map(x => <button key={x} type="button" className={mode === x ? "active" : ""} onClick={() => setMode(x)}>{x}</button>)}</div><form className="fresh-ai-composer" onSubmit={ask}><div className="fresh-ai-tools"><label title="Attach files">+<input type="file" multiple onChange={e => setFiles(Array.from(e.target.files ?? []))}/></label>{files.length > 0 && <span>{files.length} attached</span>}<small>{context.surface} · {model} · {voice ? "voice on" : "voice ready"}</small></div><textarea ref={composerRef} rows={1} value={draft} onChange={e => { setDraft(e.target.value); resize(); }} onKeyDown={keyDown} placeholder="Message Fresh AI…"/><div><span>Enter send · Shift+Enter newline</span><button type="button" onClick={() => { setVoice(v => !v); if (!voice) speak("Voice mode ready."); }} aria-label="Toggle voice">{voice ? "◉" : "◌"}</button>{loading ? <button className="stop" type="button" onClick={stop}>Stop</button> : <button type="submit" disabled={!draft.trim()}>↑</button>}</div></form><p className="fresh-ai-disclaimer">Fresh can use context, memory, research, models and approved tools. Important actions remain governed.</p></div></section></main>;
}
