import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from "react";
import { useLayout } from "../contexts/useLayout";
import { useTheme } from "../providers/ThemeProvider";
import { supabase } from "../../lib/supabase";
import { createFreshAIWorkspaceContext } from "../../core/fresh-ai/FreshAIWorkspaceContext";
import FreshAIRichText from "./FreshAIRichText";
import "./FreshAIUnified.css";

type Turn={role:"user"|"assistant";content:string;createdAt:string};
type Evidence={title:string;snippet?:string};
type DimensionalArtifact={engine:string;dimension:number;kind:string;title:string;mimeType:string;data:unknown;previewDataUrl?:string};
type AskPayload={requestId?:string;conversationId?:string|null;answer?:string;error?:string;source?:string;evidence?:Evidence[];intent?:string;image?:{url?:string;dataUrl?:string;assetId?:string;model:string;size:string};native?:boolean;provider?:string;dimensionalArtifact?:DimensionalArtifact};
const modes=["Chat","Research","Create","Build","Learn","Act"] as const;
const capabilities=[
  ["◈","Research","Find, compare and verify information"],["✦","Create","Images, media and native artifacts"],["⌘","Build","Code, systems and engineering"],
  ["◇","Analyze","Understand files, data and context"],["◎","Learn","Teach, explain and build knowledge"],["✓","Verify","Check evidence and trust"],["↗","Act","Governed actions and automation"],["▱","Organize","Projects, memory and workspace"]
] as const;

export default function FreshAIUnified(){
 const {activeRoute}=useLayout(); const {theme,toggle}=useTheme(); const context=useMemo(()=>createFreshAIWorkspaceContext(activeRoute??"/"),[activeRoute]); const isAI=(activeRoute??"").replace(/\/$/,"").toLowerCase()==="/ai";
 const [open,setOpen]=useState(isAI),[draft,setDraft]=useState(""),[turns,setTurns]=useState<Turn[]>([]),[mode,setMode]=useState<(typeof modes)[number]>("Chat"),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[image,setImage]=useState<AskPayload["image"]>(),[artifact,setArtifact]=useState<DimensionalArtifact>(),[requestId,setRequestId]=useState<string|null>(null),[conversationId,setConversationId]=useState<string|null>(null),[source,setSource]=useState<string|null>(null),[feedback,setFeedback]=useState<Record<string,number>>({}),[voice,setVoice]=useState(false),[constellation,setConstellation]=useState(false);
 const endRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLTextAreaElement|null>(null),abortRef=useRef<AbortController|null>(null),stickRef=useRef(true),messagesRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(isAI)setOpen(true)},[isAI]); useEffect(()=>{endRef.current?.scrollIntoView({behavior:loading?"auto":"smooth"})},[turns,loading]);
 useEffect(()=>{let cancelled=false;(async()=>{try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)return;const r=await fetch("/api/ai/conversations",{headers:{authorization:`Bearer ${token}`}});if(!r.ok)return;const p=await r.json() as {conversation?:{id:string}|null;turns?:Array<{role:"user"|"assistant";content:string;created_at:string}>};if(cancelled||!p.conversation)return;setConversationId(p.conversation.id);setTurns((p.turns??[]).map(x=>({role:x.role,content:x.content,createdAt:x.created_at})));}catch{/* history is optional */}})();return()=>{cancelled=true}},[]);
 useEffect(()=>{const handler=(e:Event)=>{const p=(e as CustomEvent<{prompt?:string}>).detail?.prompt;if(p){setDraft(p);setOpen(true);requestAnimationFrame(()=>inputRef.current?.focus())}};window.addEventListener("fresh-ai-open",handler);return()=>window.removeEventListener("fresh-ai-open",handler)},[]);
 function resize(){const el=inputRef.current;if(!el)return;el.style.height="auto";el.style.height=`${Math.min(el.scrollHeight,180)}px`} function onScroll(){const el=messagesRef.current;if(el)stickRef.current=el.scrollHeight-el.scrollTop-el.clientHeight<100}
 async function submit(goal:string){if(!goal||loading)return;const now=new Date().toISOString(),previous=turns.slice(-12);setTurns(v=>[...v,{role:"user",content:goal,createdAt:now},{role:"assistant",content:"",createdAt:new Date().toISOString()}]);setDraft("");requestAnimationFrame(resize);setLoading(true);setError(null);setEvidence([]);setImage(undefined);setArtifact(undefined);setSource(null);stickRef.current=true;const controller=new AbortController();abortRef.current=controller;
  try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const r=await fetch("/api/ai/ask",{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({goal,route:activeRoute??"/",mode:mode.toLowerCase(),model:"fresh-unified-1",voiceModel:context.activeVoiceModelId,conversationId,conversation:previous,workspaceContext:context,image:mode==="Create"?{size:"1024x1024",quality:"auto"}:undefined})});const payload=await r.json() as AskPayload;if(!r.ok)throw new Error(payload.error||`Fresh AI request failed (${r.status})`);setTurns(v=>{const copy=[...v],last=copy[copy.length-1];if(last?.role==="assistant")copy[copy.length-1]={...last,content:payload.answer||"Fresh AI completed the request."};return copy});setRequestId(payload.requestId??null);setConversationId(payload.conversationId??conversationId);setSource(payload.native?"Fresh Native Engine":payload.source??"Fresh AI");setEvidence(Array.isArray(payload.evidence)?payload.evidence:[]);setImage(payload.image);setArtifact(payload.dimensionalArtifact);if(voice&&payload.answer&&"speechSynthesis"in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(payload.answer));}}
  catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;const message=reason instanceof Error?reason.message:"Fresh AI could not complete that request.";setError(message);setTurns(v=>v[v.length-1]?.role==="assistant"&&!v[v.length-1].content?v.slice(0,-1):v)}finally{abortRef.current=null;setLoading(false)} }
 function ask(e?:FormEvent){e?.preventDefault();void submit(draft.trim())} function stop(){abortRef.current?.abort();setLoading(false)} function keyDown(e:KeyboardEvent<HTMLTextAreaElement>){if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void submit(draft.trim())}} function suggestion(text:string){setDraft(text);setOpen(true);requestAnimationFrame(()=>inputRef.current?.focus())} function regenerate(){const u=[...turns].reverse().find(x=>x.role==="user");if(u&&!loading)void submit(u.content)}
 async function feedbackFor(id:string,rating:number){if(feedback[id])return;try{const {data}=await supabase.auth.getSession(),token=data.session?.access_token;if(!token)return;const r=await fetch("/api/ai/feedback",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({requestId:id,rating,correct:rating>=4})});if(r.ok)setFeedback(v=>({...v,[id]:rating}))}catch{/* feedback never interrupts the answer */}} function speak(text:string){if("speechSynthesis"in window){window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
 const body=<div className="fresh-ai-unified-shell"><header><div className="fresh-ai-unified-brand"><button className="fresh-ai-unified-orb" type="button" onClick={()=>setConstellation(v=>!v)} aria-label="Open Fresh AI capabilities"><span>✦</span></button><div><strong>Fresh AI</strong><small>One intelligence. Everywhere.</small></div></div><div className="fresh-ai-unified-actions"><span>{context.featureName}</span><button type="button" onClick={toggle} aria-label="Toggle theme">{theme==="dark"?"☀":"☾"}</button>{!isAI&&<button type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button>}</div></header>
 {constellation&&<div className="fresh-ai-constellation" role="dialog" aria-label="Fresh AI capabilities"><div className="fresh-ai-constellation-head"><div><b>Fresh Intelligence</b><small>Choose a capability. Fresh keeps one intelligence underneath.</small></div><button type="button" onClick={()=>setConstellation(false)}>×</button></div><div className="fresh-ai-capability-grid">{capabilities.map(([icon,name,desc])=><button key={name} type="button" onClick={()=>{setMode(name==="Research"?"Research":name==="Create"?"Create":name==="Build"?"Build":name==="Learn"?"Learn":name==="Act"?"Act":"Chat");setConstellation(false);inputRef.current?.focus()}}><i>{icon}</i><span><b>{name}</b><small>{desc}</small></span><em>›</em></button>)}</div></div>}
 <div className="fresh-ai-unified-context"><span className="fresh-ai-context-diamond">◇</span>{context.surface}<span>·</span>{context.featureName}<span>·</span>{conversationId?`Session ${conversationId.slice(0,8)}`:"New session"}</div>
 <section className="fresh-ai-unified-messages" ref={messagesRef} onScroll={onScroll}>{turns.length===0?<div className="fresh-ai-unified-welcome"><div className="fresh-ai-welcome-crystal">✦</div><h2>What can Fresh help you do?</h2><p>One intelligence for conversation, knowledge, creation, work and action across Fresh Web Lite.</p><div className="fresh-ai-suggestions">{["Understand something","Research this","Create an image","Generate a 3D box"].map(x=><button key={x} type="button" onClick={()=>suggestion(x)}><span>◇</span>{x}</button>)}</div></div>:turns.map((t,i)=><article key={`${t.createdAt}-${i}`} className={`fresh-ai-unified-message ${t.role}`}><div className="fresh-ai-unified-avatar">{t.role==="assistant"?<span>✦</span>:"You"}</div><div><small>{t.role==="assistant"?"Fresh AI":"You"}</small>{t.role==="assistant"?<FreshAIRichText text={t.content||""}/>:<p>{t.content}</p>}{t.role==="assistant"&&i===turns.length-1&&t.content&&<nav><button type="button" onClick={()=>void navigator.clipboard?.writeText(t.content)}>Copy</button><button type="button" onClick={regenerate}>Regenerate</button><button type="button" onClick={()=>speak(t.content)}>Read aloud</button>{requestId&&<><button type="button" onClick={()=>void feedbackFor(requestId,5)} disabled={Boolean(feedback[requestId])}>👍</button><button type="button" onClick={()=>void feedbackFor(requestId,1)} disabled={Boolean(feedback[requestId])}>👎</button></>}</nav>}</div></article>)}{loading&&<div className="fresh-ai-progress"><span className="fresh-ai-progress-diamond">◇</span><div><b>Fresh is working</b><small>Understanding · retrieving · checking · preparing</small></div></div>}{evidence.length>0&&<aside className="fresh-ai-unified-evidence"><strong>✓ Verified evidence · {evidence.length}</strong>{evidence.map((item,i)=><div key={`${item.title}-${i}`}><span>{item.title}</span>{item.snippet&&<small>{item.snippet}</small>}</div>)}</aside>}{artifact&&<aside className="fresh-ai-unified-evidence"><strong>◇ Fresh Native · {artifact.dimension}D · {artifact.engine}</strong>{artifact.previewDataUrl&&<img src={artifact.previewDataUrl} alt={`${artifact.dimension}D Fresh native artifact preview`} style={{maxWidth:"100%",display:"block"}}/><small>{artifact.title} · {artifact.kind} · {artifact.mimeType}</small><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",maxHeight:220,overflow:"auto"}}>{JSON.stringify(artifact.data,null,2)}</pre></aside>}{image&&<div className="fresh-ai-unified-image"><img src={image.url||image.dataUrl} alt="Generated by Fresh AI"/><small>{image.model} · {image.size}{image.assetId?" · saved to Fresh media":""}</small></div>}{error&&<div className="fresh-ai-unified-error"><b>Fresh AI couldn't complete that request.</b><span>{error}</span><button type="button" onClick={()=>{const u=[...turns].reverse().find(x=>x.role==="user");setError(null);if(u)void submit(u.content)}}>Retry</button></div>}<div ref={endRef}/></section>
 <div className="fresh-ai-unified-composer"><div className="fresh-ai-composer-hint"><span className="fresh-ai-hint-diamond">◇</span><small>{mode} mode · Context aware</small></div><form onSubmit={ask}><button className="fresh-ai-add" type="button" onClick={()=>setConstellation(v=>!v)} aria-label="Open capabilities">＋</button><textarea ref={inputRef} rows={1} value={draft} onChange={e=>{setDraft(e.target.value);resize()}} onKeyDown={keyDown} placeholder="Message Fresh AI…"/><button className={`fresh-ai-voice ${voice?"active":""}`} type="button" onClick={()=>setVoice(v=>!v)} aria-label="Toggle voice">{voice?"◉":"◌"}</button><button className="fresh-ai-send" type="submit" disabled={!draft.trim()||loading} aria-label="Send">↑</button></form><div className="fresh-ai-composer-tools"><label className="fresh-ai-attach">⌕ Attach<input type="file" multiple onChange={e=>{const names=Array.from(e.target.files??[]).map(f=>f.name);if(names.length)setDraft(v=>`${v}${v?"\n":""}[Attached: ${names.join(", ")}]`);}}/></label><div className="fresh-ai-mode-strip">{modes.map(x=><button key={x} className={mode===x?"active":""} type="button" onClick={()=>setMode(x)}>{x}</button>)}</div><span>{loading?"Fresh is working…":"Enter to send · Shift+Enter for newline"}</span>{loading&&<button type="button" onClick={stop}>Stop</button>}</div><small className="fresh-ai-unified-status"><span>✦</span> {source||"Fresh AI"} · Native Dimensions 1D–11D · Memory · Knowledge · Research · Governed tools</small></div></div>;
 if(isAI)return <main className="fresh-ai-unified-page">{body}</main>;return <>{!open&&<button className="fresh-ai-unified-trigger" type="button" onClick={()=>setOpen(true)}><span>✦</span>Fresh AI</button>}{open&&<div className="fresh-ai-unified-overlay" role="dialog" aria-label="Fresh AI">{body}</div>}</>;
}
