import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from "react";
import { useLayout } from "../contexts/useLayout";
import { useTheme } from "../providers/ThemeProvider";
import { supabase } from "../../lib/supabase";
import { createFreshAIWorkspaceContext } from "../../core/fresh-ai/FreshAIWorkspaceContext";
import "./FreshAIMain.css";

type Turn={role:"user"|"assistant";content:string;createdAt:string};
type Evidence={title:string;snippet?:string};
type ApiResponse={requestId?:string;answer?:string;source?:string;error?:string;evidence?:Evidence[]};
const modes=["Chat","Research","Create","Build","Learn","Act"] as const;
function parseResponse(text:string,status:number):ApiResponse{try{const value=JSON.parse(text) as unknown;if(typeof value==="object"&&value!==null)return value as ApiResponse;}catch{/* non-JSON Vercel/proxy response */}const clean=text.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();return{error:clean.slice(0,500)||`Fresh AI request failed (${status}).`};}
export default function FreshAIMain(){
 const {activeRoute}=useLayout(); const {theme,toggle}=useTheme();
 const context=useMemo(()=>createFreshAIWorkspaceContext(activeRoute??"/ai"),[activeRoute]);
 const [turns,setTurns]=useState<Turn[]>([]),[draft,setDraft]=useState(""),[mode,setMode]=useState<(typeof modes)[number]>("Chat"),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[source,setSource]=useState<string|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[files,setFiles]=useState<File[]>([]);
 const abortRef=useRef<AbortController|null>(null),endRef=useRef<HTMLDivElement|null>(null),composerRef=useRef<HTMLTextAreaElement|null>(null);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:loading?"auto":"smooth",block:"end"})},[turns,loading]);
 useEffect(()=>{const open=(e:Event)=>{const p=(e as CustomEvent<{prompt?:string}>).detail?.prompt;if(p){setDraft(p);requestAnimationFrame(()=>composerRef.current?.focus())}};window.addEventListener("fresh-ai-open",open);return()=>window.removeEventListener("fresh-ai-open",open)},[]);
 function resize(){const el=composerRef.current;if(!el)return;el.style.height="auto";el.style.height=`${Math.min(el.scrollHeight,180)}px`}
 async function ask(e?:FormEvent){e?.preventDefault();const goal=draft.trim();if(!goal||loading)return;const now=new Date().toISOString();setTurns(v=>[...v,{role:"user",content:goal,createdAt:now}]);setDraft("");requestAnimationFrame(resize);setLoading(true);setError(null);setSource(null);setEvidence([]);const controller=new AbortController();abortRef.current=controller;try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const response=await fetch("/api/ai/ask",{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({goal,route:activeRoute??"/ai",mode:mode.toLowerCase(),context,conversation:turns.slice(-8),attachments:files.map(f=>({name:f.name,type:f.type,size:f.size}))})});const payload=parseResponse(await response.text(),response.status);if(!response.ok)throw new Error(payload.error??`Fresh AI request failed (${response.status}).`);const answer=typeof payload.answer==="string"?payload.answer:"Fresh AI completed the request without a text answer.";setTurns(v=>[...v,{role:"assistant",content:answer,createdAt:new Date().toISOString()}]);setSource(payload.source??null);setEvidence(Array.isArray(payload.evidence)?payload.evidence:[]);setFiles([])}catch(r){if(r instanceof DOMException&&r.name==="AbortError")return;setError(r instanceof Error?r.message:"Fresh AI could not complete that request.")}finally{abortRef.current=null;setLoading(false)}}
 function stop(){abortRef.current?.abort();setLoading(false)}
 function keyDown(e:KeyboardEvent<HTMLTextAreaElement>){if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask()}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text)}catch{/* unavailable */}}
 function regenerate(){const u=[...turns].reverse().find(t=>t.role==="user");if(u&&!loading){setDraft(u.content);requestAnimationFrame(()=>composerRef.current?.focus())}}
 return <main className="fresh-ai-main"><header className="fresh-ai-main-header"><div className="fresh-ai-main-brand"><span>F</span><div><h1>Fresh AI</h1><p>One intelligence. Everywhere.</p></div></div><div className="fresh-ai-main-actions"><span>{context.featureName}</span><button type="button" onClick={toggle}>{theme==="dark"?"☀":"☾"}</button></div></header>
 <section className="fresh-ai-conversation"><div className="fresh-ai-messages">{turns.length===0?<div className="fresh-ai-welcome"><span>F</span><h2>What can Fresh help you do?</h2><p>Ask anything. Fresh chooses the context, capabilities, models, knowledge and tools for the job.</p><div>{["Understand something","Research this","Create with me","Help me build this"].map(x=><button key={x} type="button" onClick={()=>setDraft(x)}>{x}</button>)}</div></div>:turns.map((t,i)=><article className={`fresh-ai-message ${t.role}`} key={`${t.createdAt}-${i}`}><div className="fresh-ai-avatar">{t.role==="assistant"?"F":"You"}</div><div><small>{t.role==="assistant"?"Fresh AI":"You"}</small><div className="fresh-ai-text">{t.content}</div>{t.role==="assistant"&&<nav><button type="button" onClick={()=>void copy(t.content)}>Copy</button><button type="button" onClick={regenerate}>Regenerate</button></nav>}</div></article>)}{loading&&<article className="fresh-ai-message assistant"><div className="fresh-ai-avatar">F</div><div><small>Fresh AI</small><div className="fresh-ai-thinking"><i/><i/><i/> Thinking…</div></div></article>}{error&&<div className="fresh-ai-error"><strong>Fresh AI couldn't complete that request.</strong><span>{error}</span><button type="button" onClick={()=>{setError(null);setDraft("Retry the last request")}}>Retry</button></div>}{source&&<div className="fresh-ai-meta">{source}</div>}{evidence.length>0&&<details><summary>{evidence.length} evidence items used</summary>{evidence.map((x,i)=><div key={`${x.title}-${i}`}><b>{x.title}</b>{x.snippet&&<span>{x.snippet}</span>}</div>)}</details>}<div ref={endRef}/></div>
 <div className="fresh-ai-composer-area"><div className="fresh-ai-modes">{modes.map(x=><button key={x} type="button" className={mode===x?"active":""} onClick={()=>setMode(x)}>{x}</button>)}</div><form className="fresh-ai-composer" onSubmit={ask}><div className="fresh-ai-tools"><label title="Attach files">+<input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>{files.length>0&&<span>{files.length} attached</span>}<small>{context.surface} · {context.activeModelId} · {context.activeVoiceModelId}</small></div><textarea ref={composerRef} rows={1} value={draft} onChange={e=>{setDraft(e.target.value);resize()}} onKeyDown={keyDown} placeholder="Message Fresh AI…"/><div><span>Enter send · Shift+Enter newline</span>{loading?<button className="stop" type="button" onClick={stop}>Stop</button>:<button type="submit" disabled={!draft.trim()}>↑</button>}</div></form><p>Fresh can use context, memory, research, models and approved tools. Important actions remain governed.</p></div></section></main>;
}
