import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useLayout } from "../contexts/useLayout";
import { useTheme } from "../providers/ThemeProvider";
import { supabase } from "../../lib/supabase";
import "./GlobalFreshAI.css";

type Evidence = { title: string; snippet?: string; kind?: string; publishedAt?: string };
type PipelineEvent = { stage: string; status: string; detail?: string; metrics?: Record<string, number> };
type Governance = { autonomousSelfModification?: boolean; improvementProposalsRequireApproval?: boolean; highImpactActionsRequireApproval?: boolean; reversibleImprovementsOnly?: boolean } | null;
type AskResponse = { requestId?: string; answer?: string; confidence?: string; source?: string; error?: string; evidence?: Evidence[]; pipeline?: PipelineEvent[]; governance?: Governance; verification?: { uniqueSources?: number; uniqueDomains?: number; sourceDiversity?: string; confidence?: string; contradictionsDetected?: boolean } | null; proof?: { mode?: string; evidenceCount?: number; provenance?: string } };
const kindLabel: Record<string,string>={web:"Web",news:"News",video:"Video",image:"Image",music:"Music"};
const baseSuggestions=["Research this for me","Compare the evidence","Explain this clearly","Build the next step","Find risks and unknowns","Turn this into a plan"];

export default function GlobalFreshAI(){
 const{activeRoute}=useLayout();const{theme,toggle}=useTheme();
 const[open,setOpen]=useState(false),[fullscreen,setFullscreen]=useState(false),[prompt,setPrompt]=useState(""),[answer,setAnswer]=useState<string|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[pipeline,setPipeline]=useState<PipelineEvent[]>([]),[verification,setVerification]=useState<AskResponse["verification"]>(null),[governance,setGovernance]=useState<Governance>(null),[requestId,setRequestId]=useState<string|null>(null),[feedback,setFeedback]=useState<"up"|"down"|null>(null),[source,setSource]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
 const suggestions=useMemo(()=>{const r=(activeRoute||"home").toLowerCase();if(r.includes("short"))return["Find the best ideas in this Shorts feed","Explain this video","Turn this into a post","Research this creator",...baseSuggestions.slice(4)];if(r.includes("learn"))return["Teach me this step by step","Make a study plan","Quiz me on this","Find stronger sources",...baseSuggestions.slice(4)];if(r.includes("wallet")||r.includes("crypto"))return["Explain this market move","Compare these assets","Check the risks","Summarize the latest news",...baseSuggestions.slice(4)];if(r.includes("profile"))return["Improve my profile","Find relevant connections","Organize my work","Draft my next post",...baseSuggestions.slice(4)];if(r.includes("work")||r.includes("studio"))return["Plan this project","Review my workflow","Find blockers","Build the next step",...baseSuggestions.slice(4)];return baseSuggestions},[activeRoute]);
 const capabilities=useMemo(()=>[{label:"Research",detail:"Web + evidence"},{label:"Reason",detail:"Multi-lens analysis"},{label:"Proof",detail:"Verification state"},{label:"Create",detail:"Plans + drafts"},{label:"Learn",detail:"Step-by-step"},{label:"Act",detail:"Approval-gated"}],[]);
 useEffect(()=>{const a=()=>{setOpen(true);setFullscreen(true)};const b=(e:Event)=>{const v=(e as CustomEvent<{prompt?:string}>).detail?.prompt;if(v)setPrompt(v);setOpen(true);setFullscreen(true)};window.addEventListener("fresh-ai-open",a);window.addEventListener("fresh-ai-suggestion",b);return()=>{window.removeEventListener("fresh-ai-open",a);window.removeEventListener("fresh-ai-suggestion",b)}},[]);
 async function ask(e?:FormEvent){e?.preventDefault();const goal=prompt.trim();if(!goal||loading)return;setLoading(true);setError(null);setAnswer(null);setEvidence([]);setPipeline([]);setVerification(null);setGovernance(null);setRequestId(null);setFeedback(null);setSource(null);setOpen(true);try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;const res=await fetch("/api/ai/ask",{method:"POST",headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({goal,route:activeRoute??"/"})});const p=await res.json() as AskResponse;if(!res.ok)throw new Error(p.error??`Fresh AI request failed (${res.status})`);setRequestId(typeof p.requestId==="string"?p.requestId:null);setAnswer(typeof p.answer==="string"?p.answer:"Fresh AI completed the request without a text answer.");setEvidence(Array.isArray(p.evidence)?p.evidence:[]);setPipeline(Array.isArray(p.pipeline)?p.pipeline:[]);setGovernance(p.governance&&typeof p.governance==="object"?p.governance:null);setVerification(p.verification&&typeof p.verification==="object"?p.verification:null);setSource(typeof p.source==="string"?p.source:null)}catch(x){setError(x instanceof Error?x.message:"Fresh AI could not complete that request.")}finally{setLoading(false)}}
 async function sendFeedback(value:"up"|"down"){if(!requestId||feedback||loading)return;setFeedback(value);try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)return;await fetch("/api/ai/feedback",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({requestId,rating:value==="up"?5:1,correct:value==="up"})})}catch{/* best effort */}}
 function useSuggestion(v:string){setPrompt(v);setOpen(true);setFullscreen(true)}function close(){setFullscreen(false);setOpen(false)}
 const content=<div className={fullscreen?"global-fresh-ai-shell is-fullscreen":"global-fresh-ai-shell"}>
  <div className="global-fresh-ai-header"><div className="global-fresh-ai-brand"><span className="global-fresh-ai-orb">F</span><div><strong>Fresh AI</strong><small>Research, reasoning and proof inside Fresh</small></div></div><div className="global-fresh-ai-header-actions"><button type="button" onClick={toggle}>{theme==="dark"?"☀":"☾"}</button><button type="button" onClick={()=>setFullscreen(v=>!v)}>{fullscreen?"↙":"↗"}</button><button type="button" onClick={close}>×</button></div></div>
  <div className="global-fresh-ai-capabilities" aria-label="Fresh AI capabilities">{capabilities.map(x=><div key={x.label}><strong>{x.label}</strong><span>{x.detail}</span></div>)}</div>
  <p className="global-fresh-ai-context">You are in <strong>{activeRoute||"Home"}</strong>. Fresh chooses the reasoning path automatically.</p>
  <form onSubmit={ask}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask Fresh anything…" rows={fullscreen?6:3} aria-label="Ask Fresh AI"/><div className="global-fresh-ai-form-footer"><span>{loading?"Understanding · researching · reasoning · verifying":"Fresh chooses the path automatically"}</span><button type="submit" disabled={loading||!prompt.trim()}>{loading?"Working…":"Ask Fresh AI"}</button></div></form>
  {answer&&<div className="global-fresh-ai-answer"><span>Fresh AI</span><p>{answer}</p>{source&&<small>{source}</small>}{pipeline.length>0&&<div className="global-fresh-ai-pipeline"><strong>Fresh Intelligence Path</strong><div>{pipeline.map(x=><span key={x.stage} data-status={x.status} title={x.detail}>{x.stage}</span>)}</div></div>}{verification&&<div className="global-fresh-ai-proof"><strong>Fresh Proof</strong><div>{verification.confidence??"Uncalibrated"} confidence · {verification.uniqueSources??0} independent results · {verification.uniqueDomains??0} distinct domains</div><div>{verification.sourceDiversity??"Evidence diversity not reported"}{verification.contradictionsDetected?" · conflicting evidence detected":" · cross-checked"}</div></div>}{governance&&<div className="global-fresh-ai-governance"><strong>Governance</strong><span>{governance.autonomousSelfModification?"Autonomous mutation enabled":"Self-modification locked"}</span><span>{governance.highImpactActionsRequireApproval?"High-impact actions require approval":"High-impact actions open"}</span><span>{governance.reversibleImprovementsOnly?"Improvements must be reversible":"Irreversible improvements allowed"}</span></div>}{evidence.length>0&&<div className="global-fresh-ai-evidence"><strong>Evidence used by Fresh</strong>{evidence.slice(0,8).map((x,i)=><div className="global-fresh-ai-evidence-item" key={`${i}-${x.title}`}><div><strong>{x.title}</strong><span>{kindLabel[x.kind??"web"]??"Evidence"}</span></div>{x.snippet&&<small>{x.snippet}</small>}</div>)}</div>}</div>}
  {error&&<p className="global-fresh-ai-error">Fresh AI could not complete that request. {error}</p>}
  <div className="global-fresh-ai-suggestions" aria-label="Fresh AI suggestions">{suggestions.map(x=><button key={x} type="button" onClick={()=>useSuggestion(x)}>{x}</button>)}</div>
  {requestId&&answer&&<div className="global-fresh-ai-feedback"><span>Was this useful?</span><button type="button" onClick={()=>sendFeedback("up")} disabled={Boolean(feedback)}>Helpful</button><button type="button" onClick={()=>sendFeedback("down")} disabled={Boolean(feedback)}>Needs work</button>{feedback&&<small>Feedback recorded for governed improvement.</small>}</div>}
  <div className="global-fresh-ai-bottom-actions"><span>Persistent cognitive fabric</span><span>Memory · Knowledge · Tools · Evaluation · Improvement</span></div>
  {!fullscreen&&<button className="global-fresh-ai-full" type="button" onClick={()=>setFullscreen(true)}>Open full Fresh AI →</button>}
 </div>;
 return <>{!fullscreen&&<button className="global-fresh-ai-trigger" type="button" onClick={()=>setOpen(v=>!v)}><span className="global-fresh-ai-mark">F</span><span>Fresh AI</span></button>}{open&&!fullscreen&&<aside className="global-fresh-ai-panel" aria-label="Fresh AI assistant">{content}</aside>}{fullscreen&&<div className="global-fresh-ai-overlay" role="dialog" aria-modal="true" aria-label="Fresh AI full screen workspace">{content}</div>}</>;
}
