import { FreshAIKernel, type FreshExecutionContext, type FreshMemoryStore, type FreshSkillRegistry, type FreshTruthEngine } from "./FreshAIKernel.js";
import type { Evidence, FreshConversationTurn, FreshExecutionResult, FreshIntent, FreshPipelineEvent, FreshReasoningRequest, FreshReasoningResult, FreshGoalInterpretation } from "./FreshAIArchitecture.js";
export type FreshAIRequest={requestId:string;input:string;intent?:FreshIntent;route?:string;userId?:string|null;conversation?:FreshConversationTurn[];context?:Record<string,unknown>;evidence?:Evidence[];requestedAgents?:FreshReasoningRequest["requestedAgents"];dimensions?:FreshReasoningRequest["dimensions"];approve?:boolean;execute?:boolean};
export type FreshAIResponse={requestId:string;interpretation:FreshGoalInterpretation;result:FreshReasoningResult;executions:FreshExecutionResult[];pipeline:FreshPipelineEvent[];status:"completed"|"approval-required"|"failed";error?:string};
export type FreshAIIntelligenceGatewayDependencies={skills:FreshSkillRegistry;memory:FreshMemoryStore;truth?:FreshTruthEngine;interpret?: (input:string,conversation:FreshConversationTurn[])=>Promise<FreshGoalInterpretation|null>;retrieve?: (input:string,interpretation:FreshGoalInterpretation)=>Promise<Evidence[]>};
export class FreshAIIntelligenceGateway{
 private readonly kernel:FreshAIKernel; private readonly interpretProvider:FreshAIIntelligenceGatewayDependencies["interpret"]; private readonly retrieveProvider:FreshAIIntelligenceGatewayDependencies["retrieve"];
 constructor(d:FreshAIIntelligenceGatewayDependencies){this.kernel=new FreshAIKernel(d.skills,d.memory,d.truth);this.interpretProvider=d.interpret;this.retrieveProvider=d.retrieve;}
 async handle(r:FreshAIRequest):Promise<FreshAIResponse>{const input=r.input.trim(),conversation=Array.isArray(r.conversation)?r.conversation.slice(-8):[];try{const pi=this.interpretProvider?await this.interpretProvider(input,conversation):null;const u=await this.kernel.understand({input,intent:r.intent??pi?.intent,context:{...(r.context??{}),route:r.route??"/",userId:r.userId??null,conversation,providerInterpretation:pi},evidence:r.evidence,requestedAgents:r.requestedAgents,dimensions:r.dimensions,conversation});const interpretation=pi??u.interpretation,context={...u.context,interpretation},base:FreshReasoningRequest={input,intent:interpretation.intent,context,evidence:r.evidence,requestedAgents:r.requestedAgents,dimensions:r.dimensions,conversation};const supplied=Array.isArray(r.evidence)?r.evidence:[],external=this.retrieveProvider?await this.retrieveProvider(input,interpretation):[],evidence=await this.kernel.retrieve({...base,evidence:external.length?external:supplied}),reasoning=await this.kernel.reason({...base,evidence},evidence),plan=await this.kernel.plan({...base,evidence},reasoning),verified=await this.kernel.verify({...reasoning,plan});let executions:FreshExecutionResult[]=[];if(r.execute===true&&plan.length){const ec:FreshExecutionContext={approve:r.approve,requestId:r.requestId,origin:r.route,userId:r.userId};executions=await this.kernel.execute(plan,ec)}const approvalRequired=executions.some(x=>x.status==="approval-required"),failed=executions.some(x=>x.status==="failed");return{requestId:r.requestId,interpretation,result:verified,executions,pipeline:Array.isArray(verified.pipeline)?verified.pipeline:[],status:failed?"failed":approvalRequired?"approval-required":"completed"}}catch(error){return{requestId:r.requestId,interpretation:this.fallbackInterpretation(input,r.intent),result:this.failureResult(input,error),executions:[],pipeline:[],status:"failed",error:error instanceof Error?error.message:"Fresh AI gateway failed"}}}
 private fallbackInterpretation(input:string,intent?:FreshIntent):FreshGoalInterpretation{return{intent:intent??"answer",objective:input,desiredOutcome:"Return a safe response without inventing unavailable results.",outputMode:intent==="chat"?"conversation":"answer",needsEvidence:false,needsAction:intent==="act",needsClarification:false,constraints:[],entities:[],contextDependency:"none"}}
 private failureResult(input:string,error:unknown):FreshReasoningResult{const detail=error instanceof Error?error.message:"Unknown gateway failure";return{answer:`Fresh AI could not complete this request safely: ${detail}`,claims:[],plan:[],actions:[],unknowns:[`Gateway failure while processing: ${input}`],explanation:"The gateway failed closed and did not claim an action or result it could not verify.",pipeline:[]}}
}
export const createFreshAIIntelligenceGateway=(d:FreshAIIntelligenceGatewayDependencies)=>new FreshAIIntelligenceGateway(d);
