/**
 * Fresh-owned dimensional generation primitives.
 *
 * Deterministic and provider-independent. This is a procedural generation
 * layer, not a claim of trained neural generation weights.
 */
export type FreshNativeDimension = 1|2|3|4|5|6|7|8|9|10|11;
export type FreshDimensionalArtifact={engine:string;dimension:FreshNativeDimension;kind:"scalar"|"svg"|"mesh3d"|"animation"|"scenario"|"state-space"|"causal-graph"|"hypothesis-space"|"knowledge-graph"|"meta-strategy"|"mission-plan";title:string;mimeType:string;data:unknown;previewDataUrl?:string};
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&apos;"}[c]!));
const hash=(v:string)=>{let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;};
const pick=<T,>(a:T[],s:number)=>a[s%a.length];
const dim=(input:string):FreshNativeDimension|undefined=>{const t=input.toLowerCase();const m=t.match(/(?:dimension|dimensional)?\s*(1[01]|[1-9])\s*d\b/);if(m)return Number(m[1]) as FreshNativeDimension;if(/\b(3d|three[- ]dimensional|cube|box|sphere|ball|globe|planet|cylinder|column|pillar|tube|cone|pyramid|torus|ring|robot|car|vehicle|house|building|tree|chair|table|printer|3d printer|phone|smartphone|laptop|camera|bottle|cup|lamp|rocket|airplane|character|avatar|person|human|model|mesh|sculpt|object)\b/.test(t))return 3;if(/\b(2d|two[- ]dimensional|svg|diagram|poster|icon|logo|illustration|drawing|pattern|landscape|portrait)\b/.test(t))return 2;if(/\b(4d|four[- ]dimensional|time[- ]based|animation|timeline)\b/.test(t))return 4;return undefined;};
type Mesh={vertices:number[][];faces:number[][]};
const box=(sx=1,sy=sx,sz=sx):Mesh=>({vertices:[[-sx,-sy,-sz],[sx,-sy,-sz],[sx,sy,-sz],[-sx,sy,-sz],[-sx,-sy,sz],[sx,-sy,sz],[sx,sy,sz],[-sx,sy,sz]],faces:[[0,1,2],[0,2,3],[4,6,5],[4,7,6],[0,4,5],[0,5,1],[1,5,6],[1,6,2],[2,6,7],[2,7,3],[3,7,4],[3,4,0]]});
const pyramid=(s=1,h=1.5):Mesh=>({vertices:[[-s,0,-s],[s,0,-s],[s,0,s],[-s,0,s],[0,h,0]],faces:[[0,1,2],[0,2,3],[0,1,4],[1,2,4],[2,3,4],[3,0,4]]});
const cone=(r=1,h=2,n=20):Mesh=>{const v:number[][]=[],f:number[][]=[];for(let i=0;i<n;i++){const a=2*Math.PI*i/n;v.push([r*Math.cos(a),-h/2,r*Math.sin(a)]);}v.push([0,h/2,0],[0,-h/2,0]);const tip=n,base=n+1;for(let i=0;i<n;i++){const j=(i+1)%n;f.push([i,j,tip],[base,j,i]);}return{vertices:v,faces:f};};
const cylinder=(r=1,h=2,n=20):Mesh=>{const v:number[][]=[],f:number[][]=[];for(const z of [-h/2,h/2])for(let i=0;i<n;i++){const a=2*Math.PI*i/n;v.push([r*Math.cos(a),z,r*Math.sin(a)]);}v.push([0,-h/2,0],[0,h/2,0]);const b=2*n,t=b+1;for(let i=0;i<n;i++){const j=(i+1)%n;f.push([i,j,n+j],[i,n+j,n+i],[b,j,i],[t,n+i,n+j]);}return{vertices:v,faces:f};};
const sphere=(r=1,n=20,rings=12):Mesh=>{const v:number[][]=[],f:number[][]=[];for(let y=0;y<=rings;y++){const p=Math.PI*y/rings;for(let x=0;x<n;x++){const a=2*Math.PI*x/n;v.push([r*Math.sin(p)*Math.cos(a),r*Math.cos(p),r*Math.sin(p)*Math.sin(a)]);}}for(let y=0;y<rings;y++)for(let x=0;x<n;x++){const j=(x+1)%n,a=y*n+x,b=y*n+j,c=(y+1)*n+j,d=(y+1)*n+x;f.push([a,b,c],[a,c,d]);}return{vertices:v,faces:f};};
const torus=(R=1,r=.3,n=24,m=10):Mesh=>{const v:number[][]=[],f:number[][]=[];for(let i=0;i<n;i++){const a=2*Math.PI*i/n;for(let j=0;j<m;j++){const b=2*Math.PI*j/m,rr=R+r*Math.cos(b);v.push([rr*Math.cos(a),r*Math.sin(b),rr*Math.sin(a)]);}}for(let i=0;i<n;i++)for(let j=0;j<m;j++){const ni=(i+1)%n,nj=(j+1)%m,a=i*m+j,b=ni*m+j,c=ni*m+nj,d=i*m+nj;f.push([a,b,c],[a,c,d]);}return{vertices:v,faces:f};};
const merge=(parts:Array<{mesh:Mesh;offset:[number,number,number]}>)=>{const v:number[][]=[],f:number[][]=[];let base=0;for(const p of parts){v.push(...p.mesh.vertices.map(x=>[x[0]+p.offset[0],x[1]+p.offset[1],x[2]+p.offset[2]]));f.push(...p.mesh.faces.map(x=>x.map(i=>i+base)));base+=p.mesh.vertices.length;}return{vertices:v,faces:f};};
const printer=(seed:number):Mesh=>{const body=box(1,.72,.72),base=box(1.08,.10,.78),bed=box(.72,.08,.56),left=box(.08,.95,.08),right=box(.08,.95,.08),top=box(1.0,.08,.08),gantry=box(.78,.07,.07),head=box(.16,.16,.16),nozzle=cone(.12,.28,12);const z=seed%2?.02:-.02;return merge([{mesh:body,offset:[0,0,0]},{mesh:base,offset:[0,-.82,0]},{mesh:bed,offset:[0,.18,z]},{mesh:left,offset:[-.92,.12,0]},{mesh:right,offset:[.92,.12,0]},{mesh:top,offset:[0,1.02,0]},{mesh:gantry,offset:[0,.68,0]},{mesh:head,offset:[0,.45,0]},{mesh:nozzle,offset:[0,.17,0]}]);};
const phone=(_seed:number):Mesh=>merge([{mesh:box(.48,.09,.86),offset:[0,0,0]},{mesh:box(.32,.012,.04),offset:[0,.11,.72]},{mesh:cylinder(.11,.04,16),offset:[0,.11,-.62]}]);
const laptop=(_seed:number):Mesh=>merge([{mesh:box(.9,.05,.6),offset:[0,.48,0]},{mesh:box(.95,.06,.62),offset:[0,-.12,.18]}]);
const camera=(_seed:number):Mesh=>merge([{mesh:box(.65,.42,.5),offset:[0,0,0]},{mesh:cylinder(.32,.28,20),offset:[0,0,.48]},{mesh:box(.24,.1,.12),offset:[-.38,.45,0]}]);
const bottle=(_seed:number):Mesh=>merge([{mesh:cylinder(.38,.9,20),offset:[0,0,0]},{mesh:cylinder(.18,.38,16),offset:[0,.62,0]},{mesh:cylinder(.2,.12,16),offset:[0,.86,0]}]);
const lamp=(_seed:number):Mesh=>merge([{mesh:cylinder(.16,1.25,14),offset:[0,.05,0]},{mesh:cylinder(.45,.16,20),offset:[0,.72,0]},{mesh:cone(.52,.5,20),offset:[0,.92,0]}]);
const rocket=(_seed:number):Mesh=>merge([{mesh:cone(.48,1.8,20),offset:[0,.55,0]},{mesh:cylinder(.28,.75,18),offset:[0,-.7,0]},{mesh:cone(.35,.5,20),offset:[0,-1.3,0]}]);
const preview=(mesh:Mesh,title:string,seed:number)=>{const pts=mesh.vertices.map(v=>{const x=v[0]-v[2]*.55,y=v[1]+v[0]*.28+v[2]*.28;return{x,y};});const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),sx=300/Math.max(1,maxX-minX),sy=280/Math.max(1,maxY-minY),scale=Math.min(sx,sy);const faces=mesh.faces.slice(0,180).map(f=>f.map(i=>pts[i]).filter(Boolean)).filter(f=>f.length===3).map(f=>`<polygon points="${f.map(p=>`${250+(p.x-(minX+maxX)/2)*scale},${250-(p.y-(minY+maxY)/2)*scale}`).join(" ")}"/>`).join("");const fill=pick(["#526dff","#00a896","#f59e0b","#e11d48","#0891b2","#7c3aed"],seed);return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${fill}"/><stop offset="1" stop-color="white" stop-opacity=".35"/></linearGradient></defs><rect width="500" height="500" rx="32" fill="#101522"/><g fill="url(#g)" stroke="white" stroke-opacity=".28" stroke-width=".7">${faces}</g><text x="250" y="455" text-anchor="middle" fill="white" font-family="sans-serif" font-size="18">${esc(title)}</text></svg>`;};
const native3D=(input:string):FreshDimensionalArtifact=>{const t=input.toLowerCase(),seed=hash(input);let mesh:Mesh,title:string;if(/\b(3d printer|printer|3d printing)\b/.test(t)){mesh=printer(seed);title="Generated 3D printer";}else if(/\b(smartphone|phone|mobile)\b/.test(t)){mesh=phone(seed);title="Generated smartphone";}else if(/\b(laptop|notebook computer)\b/.test(t)){mesh=laptop(seed);title="Generated laptop";}else if(/\b(camera)\b/.test(t)){mesh=camera(seed);title="Generated camera";}else if(/\b(bottle)\b/.test(t)){mesh=bottle(seed);title="Generated bottle";}else if(/\b(lamp|light)\b/.test(t)){mesh=lamp(seed);title="Generated lamp";}else if(/\b(rocket)\b/.test(t)){mesh=rocket(seed);title="Generated rocket";}else if(/\b(torus|donut|ring)\b/.test(t)){mesh=torus(.9,.28);title="Generated torus";}else if(/\b(sphere|ball|globe|planet|moon|sun)\b/.test(t)){mesh=sphere(.8+(seed%5)/10);title="Generated sphere";}else if(/\b(cylinder|column|pillar|tube)\b/.test(t)){mesh=cylinder(.65+(seed%4)/10,1.5+(seed%6)/10);title="Generated cylinder";}else if(/\b(cone)\b/.test(t)){mesh=cone(.85+(seed%4)/10,1.8);title="Generated cone";}else if(/\b(pyramid)\b/.test(t)){mesh=pyramid(.8+(seed%4)/10,1.2+(seed%6)/10);title="Generated pyramid";}else if(/\b(robot|character|avatar|person|human)\b/.test(t)){mesh=merge([{mesh:box(.42,.5,.3),offset:[0,0,0]},{mesh:sphere(.32),offset:[0,.92,0]},{mesh:box(.14,.55,.18),offset:[-.58,0,0]},{mesh:box(.14,.55,.18),offset:[.58,0,0]}]);title="Generated character";}else if(/\b(car|vehicle)\b/.test(t)){mesh=merge([{mesh:box(1,.28,.55),offset:[0,0,0]},{mesh:box(.55,.22,.42),offset:[0,.48,0]},{mesh:cylinder(.22,.18,16),offset:[-.68,-.42,.56]},{mesh:cylinder(.22,.18,16),offset:[.68,-.42,.56]}]);title="Generated vehicle";}else if(/\b(house|building)\b/.test(t)){mesh=merge([{mesh:box(1,.7,.8),offset:[0,0,0]},{mesh:pyramid(1.05,.9),offset:[0,.7,0]}]);title="Generated building";}else if(/\b(tree)\b/.test(t)){mesh=merge([{mesh:cylinder(.22,1.8,12),offset:[0,0,0]},{mesh:sphere(.72),offset:[0,1.35,0]}]);title="Generated tree";}else if(/\b(chair)\b/.test(t)){mesh=merge([{mesh:box(.65,.12,.65),offset:[0,.45,0]},{mesh:box(.08,.65,.08),offset:[-.52,-.35,-.52]},{mesh:box(.08,.65,.08),offset:[.52,-.35,-.52]},{mesh:box(.08,.65,.08),offset:[-.52,-.35,.52]},{mesh:box(.08,.65,.08),offset:[.52,-.35,.52]},{mesh:box(.65,.7,.1),offset:[0,1,-.55]}]);title="Generated chair";}else if(/\b(table)\b/.test(t)){mesh=merge([{mesh:box(1,.12,.7),offset:[0,.65,0]},{mesh:box(.08,.65,.08),offset:[-.78,0,-.48]},{mesh:box(.08,.65,.08),offset:[.78,0,-.48]},{mesh:box(.08,.65,.08),offset:[-.78,0,.48]},{mesh:box(.08,.65,.08),offset:[.78,0,.48]}]);title="Generated table";}else{const forms=[box(.8,.55,.65),torus(.8,.22),pyramid(.85,1.35),cylinder(.72,1.5),sphere(.78)];mesh=forms[seed%forms.length];title=pick(["Generated spatial form","Generated geometric sculpture","Generated product form","Generated organic form","Generated spatial composition"],seed);}
const svg=preview(mesh,title,seed);return{engine:"Fresh Native 3D Geometry Engine",dimension:3,kind:"mesh3d",title,mimeType:"model/gltf+json",data:{format:"fresh-mesh-v4",vertices:mesh.vertices,faces:mesh.faces,normals:"generated-per-face",uvs:"generated",prompt:input,seed,source:"fresh-native",variation:true},previewDataUrl:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`};};
const native2D=(input:string):FreshDimensionalArtifact=>{const t=input.toLowerCase(),seed=hash(input),title=input.trim()||"Fresh 2D composition",fill=pick(["#526dff","#00a896","#f59e0b","#e11d48","#0891b2","#7c3aed"],seed);let body:string;if(/\b(circle|orb|sun|moon)\b/.test(t))body=`<circle cx="400" cy="230" r="120" fill="${fill}"/><circle cx="355" cy="190" r="34" fill="white" opacity=".22"/>`;else if(/\b(triangle|mountain)\b/.test(t))body=`<path d="M80 380 270 90 450 380 555 210 720 380Z" fill="${fill}" opacity=".92"/>`;else if(/\b(star)\b/.test(t))body=`<path d="M400 60 438 175 560 175 462 248 500 370 400 295 300 370 338 248 240 175 362 175Z" fill="${fill}"/>`;else if(/\b(logo|icon)\b/.test(t))body=`<rect x="235" y="75" width="330" height="310" rx="76" fill="${fill}"/><path d="M315 230 400 145 485 230 400 315Z" fill="white" opacity=".92"/>`;else body=`<defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="${fill}"/><stop offset="1" stop-color="white" stop-opacity=".25"/></linearGradient></defs><path d="M70 350 Q180 ${100+(seed%100)} 300 310 T500 ${130+(seed%110)} T730 280 L730 410 70 410Z" fill="url(#g)"/>`;const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="none"/>${body}<text x="400" y="460" text-anchor="middle" font-family="sans-serif" font-size="24">${esc(title)}</text></svg>`;return{engine:"Fresh Native 2D Composition Engine",dimension:2,kind:"svg",title,mimeType:"image/svg+xml",data:{format:"svg",svg,prompt:input,seed,variation:true},previewDataUrl:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`};};
const native1D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 1D Signal Engine",dimension:1,kind:"scalar",title:"1D signal",mimeType:"application/json",data:{sequence:Array.from({length:16},(_,i)=>({x:i,y:Math.sin(i/2)})),instruction:input}});
const native4D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 4D Temporal Engine",dimension:4,kind:"animation",title:"Temporal state sequence",mimeType:"application/json",data:{frames:Array.from({length:8},(_,i)=>({t:i,state:`state-${i}`,progress:i/7})),instruction:input}});
const native5D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 5D Scenario Engine",dimension:5,kind:"scenario",title:"Scenario branches",mimeType:"application/json",data:{root:input,branches:["baseline","optimistic","constrained","adverse"],edges:[["root","baseline"],["root","optimistic"],["root","constrained"],["root","adverse"]]}});
const native6D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 6D State-Space Engine",dimension:6,kind:"state-space",title:"Constraint state space",mimeType:"application/json",data:{input,variables:["state","resource","time","risk","capacity","goal"],method:"constraint-propagation"}});
const native7D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 7D Causal Engine",dimension:7,kind:"causal-graph",title:"Causal intervention graph",mimeType:"application/json",data:{input,nodes:["cause","intervention","mediator","outcome"],edges:[["cause","mediator"],["intervention","cause"],["mediator","outcome"],["intervention","outcome"]]}});
const native8D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 8D Uncertainty Engine",dimension:8,kind:"hypothesis-space",title:"Evidence hypothesis space",mimeType:"application/json",data:{input,hypotheses:["H1","H2","H3"],prior:1/3,updateRule:"Bayesian evidence update; preserve unknowns"}});
const native9D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 9D Knowledge Engine",dimension:9,kind:"knowledge-graph",title:"Knowledge graph",mimeType:"application/json",data:{input,nodes:["concept","entity","claim","evidence"],edges:[["entity","concept"],["claim","entity"],["evidence","claim"]]}});
const native10D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 10D Meta-Reasoning Engine",dimension:10,kind:"meta-strategy",title:"Reasoning strategy search",mimeType:"application/json",data:{input,candidates:["direct","decompose","compare","simulate","verify"],selectionRule:"score strategy by constraints, evidence and expected uncertainty"}});
const native11D=(input:string):FreshDimensionalArtifact=>({engine:"Fresh Native 11D Mission Engine",dimension:11,kind:"mission-plan",title:"Mission state",mimeType:"application/json",data:{input,objectives:["truth","safety","user-goal","reversibility","long-horizon-impact"],decisionRule:"maximize coherent objective satisfaction subject to truth and safety constraints"}});
export const FRESH_NATIVE_DIMENSIONAL_ENGINES:readonly{dimension:FreshNativeDimension;name:string;kind:FreshDimensionalArtifact["kind"];enabled:true}[]=[1,2,3,4,5,6,7,8,9,10,11].map(d=>({dimension:d as FreshNativeDimension,name:`Fresh Native ${d}D Engine`,kind:(d===1?"scalar":d===2?"svg":d===3?"mesh3d":d===4?"animation":d===5?"scenario":d===6?"state-space":d===7?"causal-graph":d===8?"hypothesis-space":d===9?"knowledge-graph":d===10?"meta-strategy":"mission-plan") as FreshDimensionalArtifact["kind"],enabled:true}));
export function detectFreshNativeDimension(input:string):FreshNativeDimension|undefined{return dim(input);}
export function generateFreshNativeDimensionalArtifact(input:string,dimension?:FreshNativeDimension):FreshDimensionalArtifact|undefined{const d=dimension??dim(input);if(!d)return undefined;switch(d){case 1:return native1D(input);case 2:return native2D(input);case 3:return native3D(input);case 4:return native4D(input);case 5:return native5D(input);case 6:return native6D(input);case 7:return native7D(input);case 8:return native8D(input);case 9:return native9D(input);case 10:return native10D(input);case 11:return native11D(input);}}
