/** Provider-independent semantic retrieval and context ranking for Fresh AI. */
import type { Evidence, FreshConversationTurn } from "./FreshAIArchitecture.js";
import type { FreshMemoryRecord } from "./FreshAIKernel.js";

export type CognitiveMemoryHit = FreshMemoryRecord & { relevance:number };
const STOP_WORDS=new Set(["this","that","with","from","what","when","where","which","would","could","should","have","your","about","into","there","they","them","then","than","just","like","want","need","does","will","been","were","also","only"]);
function tokens(input:string){return[...new Set(input.toLowerCase().replace(/[^a-z0-9_\s-]/g," ").split(/\s+/).filter(x=>x.length>=3&&!STOP_WORDS.has(x)))];}
function lexicalScore(query:string,text:string){const q=tokens(query);if(!q.length)return 0;const haystack=text.toLowerCase();return q.filter(token=>haystack.includes(token)).length/q.length;}
function recencyScore(createdAt?:string){if(!createdAt)return .35;const ageDays=Math.max(0,(Date.now()-Date.parse(createdAt))/86400000);return Math.max(.05,1-Math.min(ageDays/365,.95));}
export function rankMemory(query:string,records:FreshMemoryRecord[],limit=8):CognitiveMemoryHit[]{return(records??[]).map(record=>({...record,relevance:Number((.72*lexicalScore(query,record.content)+.28*recencyScore(record.createdAt)).toFixed(4))})).filter(hit=>hit.relevance>.05).sort((a,b)=>b.relevance-a.relevance).slice(0,limit);}
export function rankEvidence(query:string,evidence:Evidence[],limit=8){return(evidence??[]).map(item=>({item,score:.65*lexicalScore(query,item.claim)+.35*Math.max(0,Math.min(1,item.confidence))})).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.item);}
export function resolveContextDependency(input:string,memories:FreshMemoryRecord[],conversation:FreshConversationTurn[]):"none"|"conversation"|"memory"|"both"{const value=input.toLowerCase();const conversationDependent=conversation.length>0&&/\b(it|that|this|they|them|he|she|yes|no|continue|again|do so|what about|same)\b/.test(value);const memoryDependent=memories.length>0&&/\b(my|our|previous|earlier|remember|project|account|settings|preference)\b/.test(value);if(conversationDependent&&memoryDependent)return"both";if(conversationDependent)return"conversation";if(memoryDependent)return"memory";return"none";}
export function buildCognitiveContext(input:string,memories:FreshMemoryRecord[],evidence:Evidence[],conversation:FreshConversationTurn[]=[]){const rankedMemory=rankMemory(input,memories,6),rankedEvidence=rankEvidence(input,evidence,6),recent=conversation.slice(-4).map(turn=>`${turn.role}: ${turn.content.slice(0,700)}`).join("\n");return[recent?`Conversation context:\n${recent}`:"",rankedMemory.length?`Durable memory (contextual, not authoritative):\n${rankedMemory.map(x=>`- ${x.content}`).join("\n")}`:"",rankedEvidence.length?`Evidence context:\n${rankedEvidence.map(x=>`- ${x.claim} [confidence ${x.confidence.toFixed(2)}]`).join("\n")}`:""].filter(Boolean).join("\n\n");}
